export const brands = [
  "Affinessence Paris",
  "Alexander Mcqueen",
  "Amouage",
  "Atkinsons",
  "BDK",
  "Boadicea",
  "Boucheron",
  "Bvlgari",
  "Caron Paris",
  "Chopard",
  "Clive Christian",
  "Creed",
  "Cupid",
  "Delmona",
  "Designer Shaik",
  "Diptyque",
  "Etro Profumi",
  "Floraiku",
  "Goutal Paris",
  "Hermetica",
  "Herve Gambs",
  "Initio",
  "Korloff Paris",
  "Lalique",
  "Le Galion",
  "Liquides Imaginaires",
  "M. Micallef",
  "Maison Francis Kurkdjian",
  "Memo",
  "Nasamatto",
  "Nicolai",
  "Orto Parisi",
  "Parfume de marly",
  "Penhaligon",
  "Robert Piguet",
  "Roja",
  "Salvador Dali",
  "Sospiro",
  "Spirit of Dubai",
  "Tiziana Terenzi",
  "V Canto",
  "Van Cleef & Arpels",
  "Widian",
  "Xerjoff",
];

export const family = [
  "aromatic",
  "citrus",
  "floral",
  "leather",
  "musk",
  "smoky",
  "spicy",
  "woody",
  "aqua",
  "fruity",
];

export const sizeInMl = [
  10, 13, 30, 35, 50, 60, 70, 75, 80, 90, 100, 125, 200, 250, 750,
];
