// all products
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

// categorized
export const PRODUCT_CATEGORY_LIST_REQUEST = "PRODUCT_CATEGORY_LIST_REQUEST";
export const PRODUCT_CATEGORY_LIST_SUCCESS = "PRODUCT_CATEGORY_LIST_SUCCESS";
export const PRODUCT_CATEGORY_LIST_FAIL = "PRODUCT_CATEGORY_LIST_FAIL";

// for-him
export const PRODUCT_FOR_HIM_LIST_REQUEST = "PRODUCT_FOR_HIM_LIST_REQUEST";
export const PRODUCT_FOR_HIM_LIST_SUCCESS = "PRODUCT_FOR_HIM_LIST_SUCCESS";
export const PRODUCT_FOR_HIM_LIST_FAIL = "PRODUCT_FOR_HIM_LIST_FAIL";

// for-her
export const PRODUCT_FOR_HER_LIST_REQUEST = "PRODUCT_FOR_HER_LIST_REQUEST";
export const PRODUCT_FOR_HER_LIST_SUCCESS = "PRODUCT_FOR_HER_LIST_SUCCESS";
export const PRODUCT_FOR_HER_LIST_FAIL = "PRODUCT_FOR_HER_LIST_FAIL";

// unisex
export const PRODUCT_UNISEX_LIST_REQUEST = "PRODUCT_UNISEX_LIST_REQUEST";
export const PRODUCT_UNISEX_LIST_SUCCESS = "PRODUCT_UNISEX_LIST_SUCCESS";
export const PRODUCT_UNISEX_LIST_FAIL = "PRODUCT_UNISEX_LIST_FAIL";

// for-home
export const PRODUCT_FOR_HOME_LIST_REQUEST = "PRODUCT_FOR_HOME_LIST_REQUEST";
export const PRODUCT_FOR_HOME_LIST_SUCCESS = "PRODUCT_FOR_HOME_LIST_SUCCESS";
export const PRODUCT_FOR_HOME_LIST_FAIL = "PRODUCT_FOR_HOME_LIST_FAIL";

// skin-care
export const PRODUCT_SKIN_CARE_LIST_REQUEST = "PRODUCT_SKIN_CARE_LIST_REQUEST";
export const PRODUCT_SKIN_CARE_LIST_SUCCESS = "PRODUCT_SKIN_CARE_LIST_SUCCESS";
export const PRODUCT_SKIN_CARE_LIST_FAIL = "PRODUCT_SKIN_CARE_LIST_FAIL";

// best sellers
export const PRODUCT_BEST_LIST_REQUEST = "PRODUCT_BEST_LIST_REQUEST";
export const PRODUCT_BEST_LIST_SUCCESS = "PRODUCT_BEST_LIST_SUCCESS";
export const PRODUCT_BEST_LIST_FAIL = "PRODUCT_BEST_LIST_FAIL";

// single product details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
